openapi: '3.0.2'
info:
  title: Polls API
  version: '1.0'
servers:
  - url: http://twitter.polls.swagger.io/api
paths:
  /polls:
    get:
      summary: Read all polls
      description: Show the list of all polls to the user
      operationId: readPolls
      responses:
        '200':
          description: polls response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Poll'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a poll
      description: Persist a poll to the database
      operationId: addPoll
      requestBody:
        description: Poll to add to the DB
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPoll'
      responses:
        '201':
          description: Created poll
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /polls/{id}:
    get:
      summary: Reads a poll by ID
      description: Show details of a specific poll
      operationId: find poll by id
      parameters:
        - name: id
          in: path
          description: ID of poll to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Poll with specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Deletes a poll by ID
      description: deletes a single poll based on specified ID
      operationId: deletePoll
      parameters:
        - name: id
          in: path
          description: ID of poll to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: poll deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Poll:
      allOf:
        - $ref: '#/components/schemas/NewPoll'
        - required:
          - id
          properties:
            id:
              type: string
              description: unique ID of the poll
    NewPoll:
      required:
        - title
        - options
      properties:
        title: 
          type: string
          description: Title of the poll
        options:
          type: array
          items: 
            type: string
        results:
          type: object
        apikey:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
    